name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 26.x
          registry-url: "https://registry.npmjs.org/"

      - name: Setup pnpm
        run: |
          npm install --global corepack@latest
          corepack enable
          corepack prepare pnpm@latest-10 --activate
          pnpm config set store-dir $(pnpm_config_cache)

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔧 Build before publishing
        run: pnpm run build

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm dlx semantic-release
